[package]
name = "procedural_dungeon"
version = "0.1.0"
authors = ["Dylan Halperin <dylan@dylemma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
